### ISSUE TITLE
Update license to adhere to NuPIC's AGPL license

### ISSUE THREAD

**Issue by rhyolight** [volitantai/nupic_from_scratch#1]
First off, I loved your demo and I appreciate the work you put into it.

However, all Numenta codebases containing patented works are licensed [AGPLv3](https://github.com/numenta/nupic/blob/master/LICENSE.txt), which means you may use it in almost any way you want as long as any code you write using it is also AGPLv3. This helps keep new innovations open to the community and allows Numenta to perform [open research](https://en.wikipedia.org/wiki/Open_science) of new theory and implementations in a transparent way.

Under the terms of the AGPL, this codebase, because it imports and uses the `nupic` python module, must also be licensed AGPL.

**Comment by rhyolight** [comment]
I'm so sorry, I was mistaken about this. Your example code is perfectly fine under the Apache 2.0.

**Comment by rhyolight** [comment]
Licensing is confusing 🤕

**Comment by volitantorg** [comment]
@rhyolight Hi Matt, all good.  This actually brings up a good point - when can we use nupic for free and when do we have to get licenses?

**Comment by rhyolight** [comment]
I think I may have been right about this issue when I created it. I will get back to you about this.

**Comment by rhyolight** [comment]
If you distribute software that depends upon NuPIC, it must either be AGPLv3, or you must have a commercial license with us. Distribution could mean bundling NuPIC with software you build and publish in any way, or even standing up a service that runs NuPIC (that's the "A" in AGPL).

**Comment by rhyolight** [comment]
@volitantorg After re-reading the [AGPL](https://www.gnu.org/licenses/agpl-3.0.en.html), I think this issue is still valid. I believe the correct interpretation of the license would be to make this codebase AGPL. 

For details on our position on the AGPL, read these blog posts from our CEO:
- [Patent Position](https://numenta.org/blog/2013/07/01/patent-position/)
- [NuPIC Commercial Licenses](https://numenta.org/blog/2013/12/16/nupic-commercial-licenses/)
- [Numenta Licensing Update AGPL](https://numenta.com/blog/2015/08/15/numenta-licensing-update-agpl/)
- [Licensing Update](https://numenta.org/blog/2015/08/17/licensing-update/)
